finecode/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', include('landingpage.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('assignments/', include('assignments.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/<int:pk>/', views.create_post, name='create_post'),
    
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings

from . import views

app_name= 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"),name="login"),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name="logout"),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User 
from classroom.models import Classroom
from PIL import Image
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    image = models.ImageField(default = 'users/profile_pics/default.jpg', upload_to='users/profile_pics/')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)

        img = Image.open(self.image.path)
        
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Profile

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields= ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', ]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm
from .models import User,Profile


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            user = User.objects.filter(username=username).first()
            Profile.objects.create(user=user)
            messages.success(request, f'Account Created Successfully for {username}')
            return redirect('users:login')
        else:
            messages.success(request, f'Error Setting up the account')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form':form})


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(data=request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(data=request.POST, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save(commit=False)
            profile = request.user.profile
            if 'image' in request.FILES:
                profile.image = request.FILES['image']
            profile.save()
            messages.success(request, f"Profile Updated !")
            return redirect('users:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'users/profile.html', context)

users/templates/users/forgot_password.html
{% extends 'user_base.html' %}
{% block title %} Forgot Password {% endblock title %}

{% block content %}
<!-- Outer Row -->
<div class="row justify-content-center">

<div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
        <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
        <div class="col-lg-6">
            <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
            </div>
            <form class="user">
                <div class="form-group">
                <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                </div>
                <a href="login.html" class="btn btn-primary btn-user btn-block">
                Reset Password
                </a>
            </form>
            <hr>
            <div class="text-center">
                <a class="small" href="register.html">Create an Account!</a>
            </div>
            <div class="text-center">
                <a class="small" href="login.html">Already have an account? Login!</a>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>

</div>

</div>

{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block content %}
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="mainapp/css/login-page.css">
</head>
<!-- Outer Row -->
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
        <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background-image: url(https://images.unsplash.com/photo-1535982330050-f1c2fb79ff78?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=667&q=80)"></div>
        <div class="col-lg-6">
            <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
            </div>
            <form class="user" method='POST'>
                {% csrf_token %}
                {{ form | crispy }}
                    <button class="btn btn-primary btn-user btn-block" type='submit'>Login</button>
            </form>
            <hr>
            <div class="text-center">
                <a class="small" href="{% url 'password_reset' %}">Forgot Password?</a>
            </div>
            <div class="text-center">
                <a class="small" href="{% url 'users:register' %}">Create an Account!</a>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>

</div>

</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'user_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title %} Login {% endblock title %}

{% block content %}
<!-- Outer Row -->
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
        <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background-image: url(https://images.unsplash.com/photo-1511629091441-ee46146481b6?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80);"></div>
        <div class="col-lg-6">
            <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Reset Password</h1>
            </div>
            <form class="user" method='POST'>
                {% csrf_token %}
                {{ form | crispy }}
                    <button class="btn btn-primary btn-user btn-block" type='submit'>Send Mail</button>
            </form>
            <hr>
            <div class="text-center">
                <a class="small" href="forgot-password.html">Forgot Password?</a>
            </div>
            <div class="text-center">
                <a class="small" href="{% url 'users:register' %}">Create an Account!</a>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>

</div>

</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'user_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title %} Login {% endblock title %}

{% block content %}
<!-- Outer Row -->
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-2">
        <div class="alert alert-info">
            Your password has been reset You can now login
        </div>
        <a class='btn btn-outline-primary' href="{% url 'users:login' %}"> Login Now !</a>
    </div>
    </div>

</div>

</div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'user_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title %} Login {% endblock title %}

{% block content %}
<!-- Outer Row -->
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
        <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background-image: url(https://images.unsplash.com/photo-1554042317-efd62f19bc95?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=337&q=80);"></div>
        <div class="col-lg-6">
            <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
            </div>
            <form class="user" method='POST'>
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary btn-user btn-block" type='submit'>Reset Password</button>
            </form>
            <hr>
            <div class="text-center">
                <a class="small" href="{% url 'users:register' %}">Create an Account!</a>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>

</div>

</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'user_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title %} Login {% endblock title %}

{% block content %}
<!-- Outer Row -->
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-1">
        <div class="alert alert-info">
        An email has been sent with instructions to reset your password !
        </div>
        <div class="row">
            <a href="{% url 'users:login' %}" class="btn btn-outline-primary ml-auto mr-1">Login</a>
            <a href="{% url 'users:register' %}" class="btn btn-outline-primary mr-auto ml-1">Register</a>
        </div>
    </div>
    </div>

</div>

</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %} Profile {% endblock title %}

{% block content %}


<div class="row">
    
    <div class="col-lg-7">
        <div class="p-3">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Update Profile!</h1>
            </div>
            <form class="user" method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                {{ user_form | crispy }}
                {{ profile_form | crispy }}
                <button type='submit' class="btn btn-small btn-primary btn-user btn-block">Update Profile</button>
            </form>
            <hr>
            
        </div>
    </div>
    <div class="col-lg-5 mt-5 p-lg-5 p-sm-3">
        ​<picture class="d-flex justify-content-center">
            <source srcset="..." type="image/png+jpg+jpeg">
            <img src="{{ request.user.profile.image.url }}" class="img-fluid img-thumbnail rounded-circle" alt="...">
        </picture>
    </div>
</div>

{% endblock content %}

users/templates/users/register copy.html
<!DOCTYPE html>
<html>
    {% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %} Register {% endblock title %}

{% block content %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <title></title>
    <meta name="description" content="" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/css/global.css' %}" />
    <link rel="stylesheet" href="{% static 'mainapp/css/login.css' %}" />

    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700&display=swap"
    />
  </head>
  <body>
    <div class="sign-up-page">
      <a class="logo-a"
        ><div class="logo-div">
          <b class="codeit-b"
            ><span>Fine</span><span class="it-span">code</span></b
          >
        </div></a
      >
      <div class="rigth-section-div">
        <div class="join-now-section">
          <div class="k-developers-joined-us-now-i">
            3k+ developers joined us, now it's your turn
          </div>
          <div class="people-pic-div">
            <div class="pic-1-div">
              <img class="male-icon" alt="" src="public/male@2x.png" />
            </div>
            <div class="pic-2-div">
              <img class="male-icon" alt="" src="public/male1@2x.png" />
            </div>
            <div class="pic-3-div">
              <img class="male-icon" alt="" src="public/female@2x.png" />
            </div>
            <div class="pic-4-div">
              <img class="male-icon" alt="" src="public/female1@2x.png" />
            </div>
          </div>
        </div>
        <img
          class="abstract-lines-icon"
          alt=""
          src="Images/Abstract Lines.png"
        />
        <div class="saly-10-div">
          <img class="saly-10-icon" alt="" src="Images/Saly-10.png" />
        </div>
        <div class="paragraph-div">
          Learn coding from scratch with best mentor and become expert in the
          next day! Supportive community, lots of expert will help you to
          improve your coding skill.
        </div>
        <b class="hero-text-b"
          ><p class="learn-coding-in">Learn Coding in</p>
          <p class="learn-coding-in">a Better Way With</p>
          <p class="expert">Expert.</p></b
        >
      </div>
      <div class="form-section-div">
        <button class="button-sign-up">
          <div class="sign-up-div">Sign Up</div>
        </button>
        <div class="already-have-an-account-log-i">
          <span class="already-have-an-account"
            ><span>Already have an account?</span
            ><span class="span"> </span></span
          ><span class="log-in-span"><a href="#" class="login-link">Log In</a></span>
        </div>
        <form action="POST" class="user"> 
            {% csrf_token %}
            {% comment %} {{ form | crispy }} {% endcomment %}
            <div class="password-div">
            <input
                name="password1"
                class="rectangle-input" 
                type="password"
                placeholder="Password"
                id="id_password1"
                autocomplete="new-password"
                required
            />
            
            </div>
            <div class="email-div">
            <input
                name="email"
                class="rectangle-input"
                type="email"
                placeholder="Email"
                id="id_email"
                required
            />
            </div>
            <div class="name-div">
                <input
                name="first_name"
                class="textinput textInput form-control rectangle-input"
                type="text"
                placeholder="First Name"
                id="id_first_name"
                required
                />
            </div>
            <div class="username-div">
                <input
                name="username"
                class="textinput textInput form-control rectangle-input"
                type="text"
                placeholder="Username"
                id="id_username"
                required
                />
            </div>
            <div class="name-div last-div">
                <input
                name="last_name"
                class="textinput textInput form-control rectangle-input last-input"
                id="id_last_name"
                type="text" 
                placeholder="Last Name"
                required
                />
            </div>
            <div class="password2-div">
                <input
                    name="password2"
                    class="rectangle-input" 
                    type="password2"
                    placeholder="Confirm Password"
                    id="id_password2"
                    autocomplete="new-password"
                    required
                />
                
            </div>
            <div class="sign-up-div1">Sign Up</div>
        </div>
        </div>
    </form>
    <script></script>
  </body>
</html>
{% endblock content %}

users/templates/users/register.html
<!DOCTYPE html>
<html>
    {% load widget_tweaks %}
{% load crispy_forms_tags %}


{% block content %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <title></title>
    <meta name="description" content="" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/css/global.css' %}" />
    <link rel="stylesheet" href="{% static 'mainapp/css/login.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700&display=swap"
    />
  </head>
  <body>
    <div class="sign-up-page">
      <a class="logo-a"
        ><div class="logo-div">
          <b class="codeit-b"
            ><span>Fine</span><span>Code</span></b
          >
        </div></a
      >
      <div class="rigth-section-div">
        <img src="{% static 'mainapp/Images/lnc.png' % }" />
        
      </div>  
      <div class="form-section-div">
        <div class="sign-up-div1">Sign Up</div>
        <form method="POST"  class="user" class="form-link"> 
            {% csrf_token %} 
            {{ form | crispy }}
            <button class="btn btn-primary btn-user btn-block ">Register</button>
            
        </div>
        </div>
    </form>
    <script></script>
  </body>
</html>
{% endblock content %}